-- CHECK IMPORTED DATA 
SELECT * 
FROM vaccinedata
LIMIT 200;



SELECT "STATE", 
	count("MANUFACTURER") as total_Vax 
FROM vaccinedata
GROUP BY "STATE"
ORDER BY total_Vax DESC;


SELECT "STATE", count("DIED") AS DIED
FROM vaccinedata
GROUP BY "STATE"
ORDER BY DIED DESC;



-- GROUP BY MANUFACTURER, HIGHEST NUMBER OF PEOPLE DIED FROM MODERNA

SELECT "MANUFACTURER", 
	count(*) as POPULATION, 
	count("HOSPITAL") as HOSPITALIZED,
	count("DIED") as DIED
FROM vaccinedata
GROUP BY "MANUFACTURER"  
ORDER BY POPULATION DESC;



-- GROUP BY SEX, MORE NUMBER OF DEATHS IN MALE

SELECT "SEX", 
	COUNT("HOSPITAL") AS HOSPITALISED,
	COUNT("DIED") AS DIED
FROM vaccinedata
GROUP BY "SEX"
ORDER BY DIED DESC;



